### PR TITLE
yo command to accept cwd uri and support explorer context menu

### PR DESCRIPTION
**Pull request by amiramw**
This mainly allows generating sub projects with yeoman in mono repos, maven child projects, etc.

Also minor cleanups were done, added category to commands and capitalize titles.

### CODE REVIEW

**Comment by amiramw** [comment]
@bfitzpat could you please review/comment on this PR?

**Comment by bfitzpat** [comment]
> @bfitzpat could you please review/comment on this PR?

Yes, adding to my list today! Thanks for the PR!

**Review by bfitzpat — CHANGES_REQUESTED** [review]
Works great - would recommend adding a note to the README.md file or create a CHANGELOG.md file to start tracking some of these new additions

**Comment by bfitzpat** [comment]
My only other question is how this will affect the current workflow. 

Right now the user simply uses the command palette to trigger a Yeoman flow. When triggered, it takes the currently open folder in the editor (i.e. workspace.rootPath) and calls the Yeoman cli from there. 

With this new method, we're forcing users to right-click on the folder they want to use as the root, effectively cutting off the way this tool used to work. 

Is there a way for us to handle both cases?

**Comment by amiramw** [comment]
Both ways still work. There is a condition and if the argument uri is not truthy the old flow is run.
`let cwd = currentFolderUri ? currentFolderUri.fsPath : workspace.rootPath;`
I'll mark the argument as optional as well.

**Comment by amiramw** [comment]
I updated the readme.

**Review by bfitzpat — APPROVED** [review]

**Pull request merged**
